-- MySQL Script generated by MySQL Workbench
-- Wed Mar 11 12:52:25 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shop` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema webshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema webshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webshop` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`brand` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `brand_UNIQUE` (`brand` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`profiles` (
  `ID` VARCHAR(255) NOT NULL,
  `segment` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`buids`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`buids` (
  `buid` INT NOT NULL,
  `profiles_ID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`buid`),
  INDEX `fk_buids_profiles1_idx` (`profiles_ID` ASC) VISIBLE,
  UNIQUE INDEX `buid_UNIQUE` (`buid` ASC) VISIBLE,
  CONSTRAINT `fk_buids_profiles1`
    FOREIGN KEY (`profiles_ID`)
    REFERENCES `shop`.`profiles` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `shop` ;

-- -----------------------------------------------------
-- Table `shop`.`cat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`cat` (
  `ID` INT NOT NULL,
  `cat` VARCHAR(255) NOT NULL,
  `subcat` VARCHAR(100) NULL DEFAULT NULL,
  `subsubcat` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `cat_UNIQUE` (`cat` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shop`.`doelgroep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`doelgroep` (
  `ID` INT NOT NULL,
  `doelgroep` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `doelgroep_UNIQUE` (`doelgroep` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shop`.`gender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`gender` (
  `ID` INT NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `gender_UNIQUE` (`gender` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shop`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`products` (
  `ID` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `price` INT NOT NULL,
  `herhaalaankopen` TINYINT NOT NULL,
  `kleur` VARCHAR(45) NULL DEFAULT NULL,
  `desc` TEXT NULL DEFAULT NULL,
  `discount` VARCHAR(45) NULL DEFAULT NULL,
  `eenheid` VARCHAR(15) NULL DEFAULT NULL,
  `inhoud` VARCHAR(20) NULL DEFAULT NULL,
  `leeftijd` VARCHAR(45) NULL DEFAULT NULL,
  `serie` VARCHAR(45) NULL DEFAULT NULL,
  `soort` VARCHAR(45) NULL DEFAULT NULL,
  `sterkte` VARCHAR(45) NULL DEFAULT NULL,
  `tax` VARCHAR(20) NULL DEFAULT NULL,
  `weekdeal` TINYINT NULL DEFAULT NULL,
  `size` VARCHAR(45) NULL DEFAULT NULL,
  `cat_ID` INT NOT NULL,
  `Gender_ID` INT NOT NULL,
  `Doelgroep_ID` INT NOT NULL,
  `brand_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `cat_ID`, `Gender_ID`, `Doelgroep_ID`, `brand_ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Products_cat1_idx` (`cat_ID` ASC) VISIBLE,
  INDEX `fk_Products_Gender1_idx` (`Gender_ID` ASC) VISIBLE,
  INDEX `fk_Products_Doelgroep1_idx` (`Doelgroep_ID` ASC) VISIBLE,
  INDEX `fk_products_brand1_idx` (`brand_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Products_cat1`
    FOREIGN KEY (`cat_ID`)
    REFERENCES `shop`.`cat` (`ID`),
  CONSTRAINT `fk_Products_Doelgroep1`
    FOREIGN KEY (`Doelgroep_ID`)
    REFERENCES `shop`.`doelgroep` (`ID`),
  CONSTRAINT `fk_Products_Gender1`
    FOREIGN KEY (`Gender_ID`)
    REFERENCES `shop`.`gender` (`ID`),
  CONSTRAINT `fk_products_brand1`
    FOREIGN KEY (`brand_ID`)
    REFERENCES `mydb`.`brand` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shop`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`sessions` (
  `ID` VARCHAR(45) NOT NULL,
  `segment` VARCHAR(45) NULL,
  `has_sale` TINYINT NULL DEFAULT NULL,
  `order` VARCHAR(255) NULL DEFAULT NULL,
  `sources` VARCHAR(45) NULL DEFAULT NULL,
  `events` VARCHAR(255) NOT NULL,
  `user_agent` VARCHAR(45) NOT NULL,
  `session_start` VARCHAR(255) NOT NULL,
  `session_end` VARCHAR(255) NOT NULL,
  `buids_idbuids` INT NOT NULL,
  PRIMARY KEY (`ID`, `buids_idbuids`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_sessions_buids1_idx` (`buids_idbuids` ASC) VISIBLE,
  CONSTRAINT `fk_sessions_buids1`
    FOREIGN KEY (`buids_idbuids`)
    REFERENCES `mydb`.`buids` (`buid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shop`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`orders` (
  `products_ID` VARCHAR(255) NOT NULL,
  `sessions_ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`products_ID`, `sessions_ID`),
  INDEX `fk_orders_sessions1_idx` (`sessions_ID` ASC) VISIBLE,
  CONSTRAINT `fk_orders_products1`
    FOREIGN KEY (`products_ID`)
    REFERENCES `shop`.`products` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_sessions1`
    FOREIGN KEY (`sessions_ID`)
    REFERENCES `shop`.`sessions` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `webshop` ;

-- -----------------------------------------------------
-- Table `webshop`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop`.`brands` (
  `id` INT NOT NULL,
  `brand` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
