-- MySQL Script generated by MySQL Workbench
-- Tue Mar 10 16:00:10 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Shop` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema webshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema webshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webshop` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shop` DEFAULT CHARACTER SET utf8 ;
USE `Shop` ;

-- -----------------------------------------------------
-- Table `Shop`.`Profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shop`.`Profiles` (
  `ID` INT NOT NULL,
  `buids` VARCHAR(200) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `buids_UNIQUE` (`buids` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Shop`.`Sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shop`.`Sessions` (
  `ID` VARCHAR(200) NOT NULL,
  `Build` VARCHAR(255) NOT NULL,
  `segment` VARCHAR(45) NULL,
  `has_sale` TINYINT NULL,
  `order` VARCHAR(255) NULL,
  `sources` VARCHAR(45) NULL,
  `events` VARCHAR(255) NOT NULL,
  `user_agent` VARCHAR(45) NOT NULL,
  `session_start` VARCHAR(255) NOT NULL,
  `session_end` VARCHAR(255) NOT NULL,
  `Profiles_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Profiles_ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `Build_UNIQUE` (`Build` ASC) VISIBLE,
  INDEX `fk_Sessions_Profiles1_idx` (`Profiles_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Sessions_Profiles1`
    FOREIGN KEY (`Profiles_ID`)
    REFERENCES `Shop`.`Profiles` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Shop`.`Brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shop`.`Brands` (
  `ID` INT NOT NULL,
  `brand` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `brand_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `brand_UNIQUE` (`brand` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Shop`.`cat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shop`.`cat` (
  `ID` INT NOT NULL,
  `cat` VARCHAR(255) NOT NULL,
  `subcat` VARCHAR(100) NULL,
  `subsubcat` VARCHAR(100) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `cat_UNIQUE` (`cat` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Shop`.`Gender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shop`.`Gender` (
  `ID` INT NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `gender_UNIQUE` (`gender` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Shop`.`Doelgroep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shop`.`Doelgroep` (
  `ID` INT NOT NULL,
  `doelgroep` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `doelgroep_UNIQUE` (`doelgroep` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Shop`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shop`.`Products` (
  `ID` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `price` INT NOT NULL,
  `herhaalaankopen` TINYINT NOT NULL,
  `kleur` VARCHAR(45) NULL,
  `desc` TEXT NULL,
  `discount` VARCHAR(45) NULL,
  `eenheid` VARCHAR(15) NULL,
  `inhoud` VARCHAR(20) NULL,
  `leeftijd` VARCHAR(45) NULL,
  `serie` VARCHAR(45) NULL,
  `soort` VARCHAR(45) NULL,
  `sterkte` VARCHAR(45) NULL,
  `tax` VARCHAR(20) NULL,
  `weekdeal` TINYINT NULL,
  `size` VARCHAR(45) NULL,
  `Brands_ID` INT NOT NULL,
  `cat_ID` INT NOT NULL,
  `Gender_ID` INT NOT NULL,
  `Doelgroep_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Brands_ID`, `cat_ID`, `Gender_ID`, `Doelgroep_ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Products_Brands1_idx` (`Brands_ID` ASC) VISIBLE,
  INDEX `fk_Products_cat1_idx` (`cat_ID` ASC) VISIBLE,
  INDEX `fk_Products_Gender1_idx` (`Gender_ID` ASC) VISIBLE,
  INDEX `fk_Products_Doelgroep1_idx` (`Doelgroep_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Products_Brands1`
    FOREIGN KEY (`Brands_ID`)
    REFERENCES `Shop`.`Brands` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_cat1`
    FOREIGN KEY (`cat_ID`)
    REFERENCES `Shop`.`cat` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_Gender1`
    FOREIGN KEY (`Gender_ID`)
    REFERENCES `Shop`.`Gender` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_Doelgroep1`
    FOREIGN KEY (`Doelgroep_ID`)
    REFERENCES `Shop`.`Doelgroep` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Shop`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shop`.`Orders` (
  `Sessions_ID` VARCHAR(45) NOT NULL,
  `Products_ID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Sessions_ID`, `Products_ID`),
  INDEX `fk_Sessions_has_Products_Products1_idx` (`Products_ID` ASC) VISIBLE,
  INDEX `fk_Sessions_has_Products_Sessions1_idx` (`Sessions_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Sessions_has_Products_Sessions1`
    FOREIGN KEY (`Sessions_ID`)
    REFERENCES `Shop`.`Sessions` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sessions_has_Products_Products1`
    FOREIGN KEY (`Products_ID`)
    REFERENCES `Shop`.`Products` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `webshop` ;

-- -----------------------------------------------------
-- Table `webshop`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop`.`brands` (
  `id` INT NOT NULL,
  `brand` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `webshop`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop`.`profiles` (
  `id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `webshop`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop`.`sessions` (
  `id` VARCHAR(255) NOT NULL,
  `build` VARCHAR(255) NULL DEFAULT NULL,
  `segment` VARCHAR(45) NULL DEFAULT NULL,
  `has_sale` TINYINT(1) NULL DEFAULT NULL,
  `order_table` VARCHAR(255) NULL DEFAULT NULL,
  `sources` VARCHAR(45) NULL DEFAULT NULL,
  `events_table` VARCHAR(255) NULL DEFAULT NULL,
  `user_agent` VARCHAR(45) NULL DEFAULT NULL,
  `session_start` VARCHAR(255) NULL DEFAULT NULL,
  `session_end` VARCHAR(255) NULL DEFAULT NULL,
  `profile_id` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `profile_id` (`profile_id` ASC) VISIBLE,
  CONSTRAINT `sessions_ibfk_1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `webshop`.`profiles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `webshop`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop`.`products` (
  `id` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `cat` VARCHAR(255) NULL DEFAULT NULL,
  `subcat` VARCHAR(255) NULL DEFAULT NULL,
  `subsubcat` VARCHAR(255) NULL DEFAULT NULL,
  `brand_id` INT NULL DEFAULT NULL,
  `gender` VARCHAR(45) NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  `herhaalaankopen` TINYINT(1) NULL DEFAULT NULL,
  `doelgroep` VARCHAR(45) NULL DEFAULT NULL,
  `kleur` VARCHAR(45) NULL DEFAULT NULL,
  `descr` VARCHAR(255) NULL DEFAULT NULL,
  `discount` VARCHAR(255) NULL DEFAULT NULL,
  `eenheid` VARCHAR(15) NULL DEFAULT NULL,
  `inhoud` VARCHAR(20) NULL DEFAULT NULL,
  `leeftijd` VARCHAR(45) NULL DEFAULT NULL,
  `serie` VARCHAR(45) NULL DEFAULT NULL,
  `soort` VARCHAR(45) NULL DEFAULT NULL,
  `sterkte` VARCHAR(45) NULL DEFAULT NULL,
  `tax` VARCHAR(20) NULL DEFAULT NULL,
  `weekdeal` TINYINT(1) NULL DEFAULT NULL,
  `size` VARCHAR(45) NULL DEFAULT NULL,
  `recommendable` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `webshop`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop`.`orders` (
  `sessions_id` VARCHAR(255) NULL DEFAULT NULL,
  `products_id` VARCHAR(45) NULL DEFAULT NULL,
  INDEX `sessions_id` (`sessions_id` ASC) VISIBLE,
  INDEX `products_id` (`products_id` ASC) VISIBLE,
  CONSTRAINT `orders_ibfk_1`
    FOREIGN KEY (`sessions_id`)
    REFERENCES `webshop`.`sessions` (`id`),
  CONSTRAINT `orders_ibfk_2`
    FOREIGN KEY (`products_id`)
    REFERENCES `webshop`.`products` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `shop` ;

-- -----------------------------------------------------
-- Table `shop`.`cat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`cat` (
  `ID` INT NOT NULL,
  `cat` VARCHAR(255) NOT NULL,
  `subcat` VARCHAR(100) NULL DEFAULT NULL,
  `subsubcat` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `cat_UNIQUE` (`cat` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shop`.`doelgroep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`doelgroep` (
  `ID` INT NOT NULL,
  `doelgroep` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `doelgroep_UNIQUE` (`doelgroep` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shop`.`gender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`gender` (
  `ID` INT NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `gender_UNIQUE` (`gender` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shop`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`products` (
  `ID` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `cat` VARCHAR(255) NULL DEFAULT NULL,
  `subcat` VARCHAR(255) NULL DEFAULT NULL,
  `subsubcat` VARCHAR(255) NULL DEFAULT NULL,
  `brand` VARCHAR(255) NULL DEFAULT NULL,
  `gender` VARCHAR(45) NULL DEFAULT NULL,
  `price` INT NOT NULL,
  `herhaalaankopen` TINYINT NOT NULL,
  `doelgroep` VARCHAR(45) NULL DEFAULT NULL,
  `kleur` VARCHAR(45) NULL DEFAULT NULL,
  `desc` TEXT NULL DEFAULT NULL,
  `discount` VARCHAR(45) NULL DEFAULT NULL,
  `eenheid` VARCHAR(15) NULL DEFAULT NULL,
  `inhoud` VARCHAR(20) NULL DEFAULT NULL,
  `leeftijd` VARCHAR(45) NULL DEFAULT NULL,
  `serie` VARCHAR(45) NULL DEFAULT NULL,
  `soort` VARCHAR(45) NULL DEFAULT NULL,
  `sterkte` VARCHAR(45) NULL DEFAULT NULL,
  `tax` VARCHAR(20) NULL DEFAULT NULL,
  `weekdeal` TINYINT NULL DEFAULT NULL,
  `size` VARCHAR(45) NULL DEFAULT NULL,
  `Gender_gender` INT NOT NULL,
  `Brands_ID` INT NOT NULL,
  `cat_ID` INT NOT NULL,
  `Gender_ID` INT NOT NULL,
  `Doelgroep_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Gender_gender`, `Brands_ID`, `cat_ID`, `Gender_ID`, `Doelgroep_ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Products_Brands1_idx` (`Brands_ID` ASC) VISIBLE,
  INDEX `fk_Products_cat1_idx` (`cat_ID` ASC) VISIBLE,
  INDEX `fk_Products_Gender1_idx` (`Gender_ID` ASC) VISIBLE,
  INDEX `fk_Products_Doelgroep1_idx` (`Doelgroep_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Products_Brands1`
    FOREIGN KEY (`Brands_ID`)
    REFERENCES `shop`.`brands` (`ID`),
  CONSTRAINT `fk_Products_cat1`
    FOREIGN KEY (`cat_ID`)
    REFERENCES `shop`.`cat` (`ID`),
  CONSTRAINT `fk_Products_Doelgroep1`
    FOREIGN KEY (`Doelgroep_ID`)
    REFERENCES `shop`.`doelgroep` (`ID`),
  CONSTRAINT `fk_Products_Gender1`
    FOREIGN KEY (`Gender_ID`)
    REFERENCES `shop`.`gender` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shop`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`profiles` (
  `ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shop`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`sessions` (
  `ID` VARCHAR(45) NOT NULL,
  `Build` VARCHAR(255) NOT NULL,
  `segment` VARCHAR(45) NULL DEFAULT NULL,
  `has_sale` TINYINT NULL DEFAULT NULL,
  `order` VARCHAR(255) NULL DEFAULT NULL,
  `sources` VARCHAR(45) NULL DEFAULT NULL,
  `events` VARCHAR(255) NOT NULL,
  `user_agent` VARCHAR(45) NOT NULL,
  `session_start` VARCHAR(255) NOT NULL,
  `session_end` VARCHAR(255) NOT NULL,
  `Profiles_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Profiles_ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `Build_UNIQUE` (`Build` ASC) VISIBLE,
  INDEX `fk_Sessions_Profiles1_idx` (`Profiles_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Sessions_Profiles1`
    FOREIGN KEY (`Profiles_ID`)
    REFERENCES `shop`.`profiles` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shop`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`orders` (
  `Sessions_ID` VARCHAR(45) NOT NULL,
  `Products_ID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Sessions_ID`, `Products_ID`),
  INDEX `fk_Sessions_has_Products_Products1_idx` (`Products_ID` ASC) VISIBLE,
  INDEX `fk_Sessions_has_Products_Sessions1_idx` (`Sessions_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Sessions_has_Products_Products1`
    FOREIGN KEY (`Products_ID`)
    REFERENCES `shop`.`products` (`ID`),
  CONSTRAINT `fk_Sessions_has_Products_Sessions1`
    FOREIGN KEY (`Sessions_ID`)
    REFERENCES `shop`.`sessions` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
